name: Jest + SonarCloud - NodeJS CI

on:

  pull_request:
    branches: 
      - '**'
      - '!documentacao'

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    container: node:14


    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres

          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

            
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci


      - name: Database Migration
        run: npx sequelize db:drop 
          && npx sequelize db:create
          && npx sequelize db:migrate
        env:
          PG_HOST: postgres
          PG_PORT: 5432

      - name: Run Tests
        run: npm test
        env:
          PG_HOST: postgres
          PG_PORT: 5432

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


